CXX      = g++
CXXFLAGS = -g -std=c++17 -Wall -Werror -pedantic-errors -fmessage-length=0

all:
	g++ testrbt.cpp node.h rbtree.h tree.h treeprinter.h -o testrbt -g -std=c++17 -Wall -Werror -pedantic-errors -fmessage-length=0
clean:
	rm -f *.gch testrbt

# g++ testrbt.cpp node.h rbtree.h tree.h treeprinter.h -g -std=c++17 -Wall -Werror -pedantic-errors -fmessage-length=0